
dist: trusty
sudo: true
language: cpp

install:
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
sudo apt-get update -qq
if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

compiler:
- gcc

script:
- cd test && mkdir build && cd build && cmake .. && make
