dist: trusty
sudo: required
language: cpp

matrix:
  include:
    
    # Gcc49
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CONFIG=Gcc49"
    
    # Gcc7_Debug_gcov
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
         - MATRIX_EVAL="CONFIG=Gcc7_Debug_gcov"
      before_install:
         - pip install --user cpp-coveralls
         - chmod +x scripts/test.sh
         - chmod +x scripts/bench.sh
         - eval "${MATRIX_EVAL}"

    # clang4
    - os: linux
      env:
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CONFIG=clang4"

    # clang5_Debug
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CONFIG=clang5_Debug"

    # clang5_thread_sanitizer
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CONFIG=clang5_thread_sanitizer"

    # Gcc7_thread_sanitizer
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CONFIG=Gcc7_thread_sanitizer"

    # Gcc7_Debug_cpp14
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="COONFIG=Gcc7_Debug_cpp14"

    # Gcc7_Debug_cpp17
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CONFIG=Gcc7_Debug_cpp17"


before_install:
    - chmod +x scripts/test.sh
    - chmod +x scripts/bench.sh
    - eval "${MATRIX_EVAL}"

script:
  - scripts/test.sh $CONFIG

